Table users {
  user_id varchar [pk] // Firebase UID
  first_name varchar
  last_name varchar
  email varchar [unique]
}

Table admins {
  admin_id varchar [pk] // Firebase UID
  first_name varchar
  last_name varchar
  email varchar [unique]
}

Table dental_images {
  image_id int [pk, increment]
  user_id varchar [ref: > users.user_id]
  image_url varchar
}

Table admin_view_results {
  admin_id varchar [ref: > admins.admin_id]
  result_id int [ref: > diagnosis_results.result_id]
}

Table diagnosis_results {
  result_id int [pk, increment]
  image_id int [ref: > dental_images.image_id]
  calculus_detected bool
  calculus_amount int
  oral_health_status varchar
}

// Only if status is unhealthy
Table appointments {
  appointment_id int [pk, increment]
  user_id varchar [ref: > users.user_id]
  admin_id varchar [ref: > admins.admin_id]
  result_id int [ref: > diagnosis_results.result_id]
  appointment_date date
  appointment_time time
  status varchar
  created_on timestamp
  updated_at timestamp
}
